name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # JDK Setting
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

        # Grant gradlew Permission
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

        # Gradle Build With Test
      - name: Build with Gradle
        run: ./gradlew build

        # Image Tagging
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ${{ secrets.DOCKER_REPOSITORY }}/atension
          tag-semver: |
            {{version}}
            {{major}}.{{minor}}

        # Docker Buildx Setup
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

        # Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

        # Docker Build and Push
      - name: Docker build & push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}

        # Workflow_dispatch
      - run: gh api /repos/a-tension/Deploy/dispatches -f event_type='backend-event'
        env:
          GITHUB_TOKEN: ${{ secrets.DISPATCH_KEY }}
